# Hypercube optimization
algo: 'hc'

# Architecture
arch: cResNet18

# ===== Dataset ===== #
dataset: CIFAR10
name: resnet18_cifar10_hypercube_noreg

# ===== Learning Rate Policy ======== #
optimizer: adam
lr: 0.01
#lr_policy: cosine_lr

# ===== Network training config ===== #
epochs: 10
weight_decay: 0.0 #0.0001
momentum: 0.9
batch_size: 128

# ===== Sparsity =========== #
conv_type: SubnetConv
bn_type: NonAffineBatchNorm
freeze_weights: True
prune_rate: 0.0
init: signed_constant
score_init: unif
scale_fan: True


# ===== Rounding ===== #
round: naive
noise: True
noise_ratio: 0


# ===== Regularization ===== #
regularization: False
lmbda: 0.000001 #0.000001


# ===== Hardware setup ===== #
workers: 4
gpu: 1

