subfolder: tiny_res101_weight_training
trial_num: 1


# algorithm
algo: 'training'

# Architecture
arch: ResNet101

# ===== Dataset ===== #
dataset: TinyImageNet
name: tiny_resnet101_training

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.2
lr_policy: multistep_lr #cosine_lr #constant_lr

# ===== Network training config ===== #
epochs: 200
wd: 0.0001
momentum: 0.9
batch_size: 256

weight_training: True

# ===== Sparsity =========== #
conv_type: SubnetConv
bn_type: NonAffineBatchNorm
freeze_weights: True
prune_rate: -1
init: kaiming_normal
scale_fan: True

# ===== Hardware setup ===== #
workers: 4
gpu: 0

