# Edge-popup version
algo: 'ep'

# Architecture
arch: Conv4

# ===== Dataset ===== #
dataset: CIFAR10
name: conv4_ep_sc

# ===== Learning Rate Policy ======== #
optimizer: adam #sgd
lr: 0.00001 #0.1
lr_policy: multistep_lr # cosine_lr
lr_gamma: 0.7
lr_adjust: 20 #20


# ===== Network training config ===== #
epochs: 150
weight_decay: 0.0001
momentum: 0.9
batch_size: 128

# ===== Sparsity =========== #
conv_type: SubnetConv
bn_type: NonAffineBatchNorm
freeze_weights: True
prune_rate: 0.5
init: signed_constant
scale_fan: True

# ===== Hardware setup ===== #
workers: 4
gpu: 0
