# Edge-popup version
algo: 'ep'

# Architecture
arch: Conv4Normal

# Mode
mode: training

# ===== Dataset ===== #
#data: /mnt
set: CIFAR10
name: conv4_kn_unsigned

# ===== Learning Rate Policy ======== #
optimizer: adam
lr: 0.001
lr_policy: None

# ===== Network training config ===== #
epochs: 200
weight_decay: 0.0001
momentum: 0.9
batch_size: 128

# ===== Hardware setup ===== #
workers: 4

